### ISSUE TITLE
발표자료 : 24년 9월 3주차 발표자료 

### ISSUE THREAD

**Issue by rimi3226** [capstoneA/Documents#1]
# 발표자료 내용
### 🔹 메인 기능
- 사람이 걷는 속도에 맞춰서 한 걸음 내딛을 때마다 함께 움직이는 보행기
- 핸들에 부착된 압력센서를 통해 저항값을 기준으로 모터 제어
    - 각 핸들에 압력센서를 8개 정도 달아서 미는 것과 꽉 잡는 것, 당기는 것을 판별
- 영상처리를 통해서 핸들 압력과 이동속도 간의 상관관계 파악
    - 핸들 압력을 통한 모터 구동의 보정용도로 영상처리를 활용
    - 상시 동작 X , 보행기 충전 시 녹화된 영상을 통해 영상처리 진행 -> 전력 최소화
### 🔹 서브 기능
- 보폭 분석 후 이상 징후, 보폭 속도 및 걸음 습관 데이터 집계해서 시각화하기
- 손잡이 길이를 마음대로 정할 수 있도록 변경
- 브레이크 및 비상 정지 버튼 추가
- 야간을 대비하는 라이트 추가

## 역할 분담
- 김준범
    - 전체적인 보행기 구조 설계
    - 손잡이 길이를 마음대로 정할 수 있도록 변경
    - 브레이크 및 비상 정지 버튼 추가
    - 야간을 대비하는 라이트 추가
- 이진성
    - 파츠 3D 설계
    - 마이크로프로세서 구동 모델 설계
    - 마이크로프로세서, 라즈베리파이 간 통신모델
- 이효림
    - 녹화된 영상에서 보폭 분석 진행
    - 이상 징후, 보폭 속도 및 걸음 습관 데이터 집계해서 시각화하기
- 박소윤
    - 라즈베리파이 셋업, 영상 녹화 프로세스 및 영상 처리 프로세스 개발
    - 녹화 + 저장 프로세스 - 라즈베리파이 (영상처리)
    - 실시간 동작 프로세스 - 마이크로프로세서 (모터구동 등)

## 구현 방법
- 구조 설계 측면
- 각자 구현 방법 세워서 진성이에게 보내면 진성이가 취합

## 구현 계획
- 시작일 : 24년 9월 30일
- 마감일 : 24년 11월 22일
- 각자 구현 계획 세워서 진성이에게 보내면 진성이가 취합

**Comment by Bina-Lee** [comment]
.
